
name: math_utils
version: 0.0.1
description: Um pacote simples para calcular a média de uma lista de números.
author: Seu Nome <seuemail@example.com>
homepage: https://github.com/seuusuario/math_utils